Develop
Bohdan1337max/TicTacToe pull request #1
Opened 2023-07-31 12:46 UTC by Bohdan1337max

2023-08-06 13:43 UTC, Bohdan1337max commented
Nick Hi

2023-08-18 20:07 UTC, QQumba requested changes

2023-08-18 20:07 UTC, QQumba commented on ServerAPI/Controllers/LongPollingController.cs
> +
extra white spaces, on the beginning of the file as well

2023-08-18 20:07 UTC, QQumba commented on ServerAPI/Controllers/TicTacToeController.cs
> +                return NotFound("Room is Full");
It's not really relevant in case of the tic tac toe game server, but usualy you send 404 when you try to access something that doesn't exists 

Imagine that your tic tac toe server supports multiple game sessions aka rooms, and if you try to find the room lets say by its name, then 404 wll be an appropriate error

2023-08-18 20:07 UTC, QQumba commented on ServerAPI/Controllers/TicTacToeController.cs
> +
white spaces (˘･_･˘)

2023-08-18 20:07 UTC, QQumba commented on ServerAPI/GameState.cs
> +    //public int PointerCoordinateX { get; set; }
if you realy love your unsused code, create a new branch for it and just store different version of it, or let it live in your heart, and the commit history of course

2023-08-18 20:07 UTC, QQumba commented on ServerAPI/Pixel.cs
> +    public Char _char { get; set; } = ' ';
_underscore names is for private fields

2023-08-18 20:07 UTC, QQumba commented on TicTacToe/FileHandler.cs
> +    private string _pathO = @".\Models\O.txt";
why not both are statis?
even more you can make them const

2023-08-18 20:07 UTC, QQumba commented on TicTacToe/Game.cs
> +    public GameSigns Winner;
make it property

2023-08-18 20:07 UTC, QQumba commented on TicTacToe/GameState.cs
> +    //public int PointerCoordinateY { get; set; }
commented code

2023-08-18 20:07 UTC, QQumba commented on ServerAPI/Pixel.cs
why you need pixels on the server?

2023-08-18 20:07 UTC, QQumba commented on TicTacToe/Pixel.cs
> +    public Char _char { get; set; } = ' ';
naming

2023-08-18 20:14 UTC, Bohdan1337max commented on ServerAPI/Controllers/TicTacToeController.cs
> +                return NotFound("Room is Full");
.I.

2023-08-18 20:31 UTC, merged